#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# Dependency-free build script for the Sarvam AI assistant NVDA add-on.
#
# Usage:
#   python build.py            build the .nvda-addon and copy it to Downloads
#   python build.py --no-copy  build only, do not copy to Downloads
#   python build.py --pot      (re)generate the translation template only
#
# A .nvda-addon file is simply a ZIP archive whose root contains manifest.ini
# plus the plugin folders, so no third-party tooling is required.

import os
import re
import sys
import zipfile
import shutil

ROOT = os.path.dirname(os.path.abspath(__file__))
ADDON_DIR = os.path.join(ROOT, "addon")

sys.path.insert(0, ROOT)
import buildVars  # noqa: E402

INFO = buildVars.addon_info


def generate_manifest():
	"""Write addon/manifest.ini from buildVars."""
	manifest = os.path.join(ADDON_DIR, "manifest.ini")
	lines = [
		"; NVDA add-on manifest - generated by build.py. Do not edit by hand.",
		'name = %s' % INFO["addon_name"],
		'summary = "%s"' % INFO["addon_summary"],
		'description = "%s"' % INFO["addon_description"].replace('"', "'"),
		'author = "%s"' % INFO["addon_author"],
		'version = %s' % INFO["addon_version"],
		'url = %s' % INFO["addon_url"],
		'sourceURL = %s' % INFO["addon_sourceURL"],
		'docFileName = %s' % INFO["addon_docFileName"],
		'minimumNVDAVersion = %s' % INFO["addon_minimumNVDAVersion"],
		'lastTestedNVDAVersion = %s' % INFO["addon_lastTestedNVDAVersion"],
		'license = %s' % INFO["addon_license"],
		'licenseURL = %s' % INFO["addon_licenseURL"],
	]
	if INFO.get("addon_updateChannel"):
		lines.append('updateChannel = %s' % INFO["addon_updateChannel"])
	with open(manifest, "w", encoding="utf-8") as f:
		f.write("\n".join(lines) + "\n")
	print("Generated %s" % manifest)
	return manifest


_STRING_RE = re.compile(r"_\(\s*(?:u?\"((?:[^\"\\]|\\.)*)\"|u?'((?:[^'\\]|\\.)*)')\s*\)")


def generate_pot():
	"""Scan the source for _( "..." ) strings and emit a gettext .pot template."""
	messages = []
	seen = set()
	for base in buildVars.i18nSources:
		for dirpath, _dirs, files in os.walk(os.path.join(ROOT, base)):
			for name in files:
				if not name.endswith(".py"):
					continue
				path = os.path.join(dirpath, name)
				with open(path, "r", encoding="utf-8", errors="replace") as f:
					for lineno, line in enumerate(f, 1):
						for m in _STRING_RE.finditer(line):
							msg = m.group(1) or m.group(2) or ""
							if msg and msg not in seen:
								seen.add(msg)
								rel = os.path.relpath(path, ROOT).replace("\\", "/")
								messages.append((msg, "%s:%d" % (rel, lineno)))
	locale_dir = os.path.join(ADDON_DIR, "locale")
	os.makedirs(locale_dir, exist_ok=True)
	pot = os.path.join(locale_dir, "sarvamAI.pot")
	with open(pot, "w", encoding="utf-8") as f:
		f.write('msgid ""\nmsgstr ""\n')
		f.write('"Project-Id-Version: %s %s\\n"\n' % (INFO["addon_name"], INFO["addon_version"]))
		f.write('"Content-Type: text/plain; charset=UTF-8\\n"\n')
		f.write('"Content-Transfer-Encoding: 8bit\\n"\n\n')
		for msg, ref in messages:
			escaped = msg.replace("\\", "\\\\").replace('"', '\\"')
			f.write("#: %s\n" % ref)
			f.write('msgid "%s"\n' % escaped)
			f.write('msgstr ""\n\n')
	print("Generated %s (%d strings)" % (pot, len(messages)))
	return pot


def package():
	version = INFO["addon_version"]
	out_name = "%s-%s.nvda-addon" % (INFO["addon_summary"].replace(" ", ""), version)
	out_path = os.path.join(ROOT, out_name)
	if os.path.exists(out_path):
		os.remove(out_path)
	with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
		for dirpath, _dirs, files in os.walk(ADDON_DIR):
			for name in files:
				if name.endswith((".pyc", ".pyo")) or "__pycache__" in dirpath:
					continue
				full = os.path.join(dirpath, name)
				arc = os.path.relpath(full, ADDON_DIR)
				zf.write(full, arc)
	print("Built %s (%d bytes)" % (out_path, os.path.getsize(out_path)))
	return out_path


def copy_to_downloads(path):
	downloads = os.path.join(os.path.expanduser("~"), "Downloads")
	if not os.path.isdir(downloads):
		print("Downloads folder not found; skipping copy.")
		return
	dest = os.path.join(downloads, os.path.basename(path))
	shutil.copy2(path, dest)
	print("Copied to %s" % dest)


def main(argv):
	if "--pot" in argv:
		generate_pot()
		return
	generate_manifest()
	generate_pot()
	out = package()
	if "--no-copy" not in argv:
		copy_to_downloads(out)


if __name__ == "__main__":
	main(sys.argv[1:])
